### ISSUE TITLE
Sorry for contacting this way

### ISSUE THREAD

**Issue by zTechSoul** [FS-NulL/MiscMaps#1]
Hello,
First of all my apologies for contacting you this way.

Seems like the following extension for Visual Studio 2019: "Structure Visualizer In Map Mode Scrollbar" is published under your account.
I'm a huge fan of it and so used to using it that I feel uncomfortable switching to VS 2022 given this extension is not available AND there seem to be no alternative built in.

Curious if you have plans rolling out the extension for 2022 OR if not, where I could find source code for 2019 so that I can update it to fit VS 2022.

Thank you.

**Comment by FS-NulL** [comment]
See here:
https://marketplace.visualstudio.com/items?itemName=BorisRoux.StructureVisualizer2022-0
